name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [amd64, arm64]  # Add other architectures as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22' 

      - name: Build for ${{ matrix.arch }}
        run: |
          GOARCH=${{ matrix.arch }} go build -o build/ftransfer-${{ matrix.arch }} ./... 

      - name: Create Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/ftransfer-${{ matrix.arch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
